// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-VUlRVXFnU6wAXn_F1SpTBo5PQqp8oek',
    appId: '1:113100959619:web:3522ef1b2bf5cf4c7550b6',
    messagingSenderId: '113100959619',
    projectId: 'bitirme-e0272',
    authDomain: 'bitirme-e0272.firebaseapp.com',
    storageBucket: 'bitirme-e0272.firebasestorage.app',
    measurementId: 'G-FMTV8MGE5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmo64_TcfWaW4zkqlHI6P8v9hldh1poVg',
    appId: '1:113100959619:android:b0a3ffc621a1cd167550b6',
    messagingSenderId: '113100959619',
    projectId: 'bitirme-e0272',
    storageBucket: 'bitirme-e0272.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYOXt1Jtz5aNjcg7zJJ_wb4H61BIqR6iI',
    appId: '1:113100959619:ios:f1feb0ce6a28a2a17550b6',
    messagingSenderId: '113100959619',
    projectId: 'bitirme-e0272',
    storageBucket: 'bitirme-e0272.firebasestorage.app',
    iosBundleId: 'com.example.bitirme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYOXt1Jtz5aNjcg7zJJ_wb4H61BIqR6iI',
    appId: '1:113100959619:ios:f1feb0ce6a28a2a17550b6',
    messagingSenderId: '113100959619',
    projectId: 'bitirme-e0272',
    storageBucket: 'bitirme-e0272.firebasestorage.app',
    iosBundleId: 'com.example.bitirme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-VUlRVXFnU6wAXn_F1SpTBo5PQqp8oek',
    appId: '1:113100959619:web:d499c6d5913632cb7550b6',
    messagingSenderId: '113100959619',
    projectId: 'bitirme-e0272',
    authDomain: 'bitirme-e0272.firebaseapp.com',
    storageBucket: 'bitirme-e0272.firebasestorage.app',
    measurementId: 'G-VDYQ33M65C',
  );
}
